# Generated by Django 5.1.7 on 2025-03-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('artist', 'Artist'), ('gallery_admin', 'Gallery Administrator'), ('normal_user', 'Normal User')], default='normal_user', max_length=20),
        ),
    ]
