# Generated by Django 5.1.5 on 2025-02-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_artwork_artist_profile_delete_artist_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='anonymous', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='anonymous', max_length=20),
        ),
    ]
