# Generated by Django 5.1.7 on 2025-03-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_customuser_bio_customuser_residence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='residence',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
