# Generated by Django 5.1.5 on 2025-02-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_artwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='created_at',
        ),
        migrations.AddField(
            model_name='artwork',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
