# Generated by Django 5.1.5 on 2025-03-10 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_delete_artwork'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
