# Generated by Django 5.1.7 on 2025-04-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_mpesapayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MpesaPayment',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
