# Generated by Django 5.1.7 on 2025-04-08 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galleries', '0002_delete_galleries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='date',
        ),
        migrations.RemoveField(
            model_name='events',
            name='name',
        ),
        migrations.AddField(
            model_name='events',
            name='date_of_event',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='events',
            name='poster_image',
            field=models.ImageField(null=True, upload_to='event_posters'),
        ),
        migrations.AddField(
            model_name='events',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
