# Generated by Django 5.1.7 on 2025-04-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galleries', '0003_remove_events_date_remove_events_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_description',
            field=models.TextField(null=True),
        ),
    ]
