# Generated by Django 5.1.7 on 2025-04-20 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galleries', '0004_events_event_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='title',
            new_name='event_title',
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ticket_quantity', models.IntegerField(null=True)),
                ('ticket_status', models.CharField(max_length=20, null=True)),
                ('ticket_code', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Galleries.events')),
                ('ticket_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
