# Generated by Django 5.1.7 on 2025-04-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galleries', '0005_rename_title_events_event_title_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='ticket_code',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='ticket_quantity',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='ticket_status',
        ),
        migrations.AddField(
            model_name='tickets',
            name='ticket_pdf',
            field=models.ImageField(null=True, upload_to='tickets'),
        ),
    ]
