# Generated by Django 5.1.7 on 2025-04-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galleries', '0006_remove_tickets_ticket_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='venue',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
