# Generated by Django 5.1.7 on 2025-04-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galleries', '0007_events_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='event_title',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='ticket_owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='ticket_pdf',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='ticket_price',
        ),
        migrations.AddField(
            model_name='tickets',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='status',
            field=models.CharField(default='Pending', max_length=15),
        ),
    ]
