# Generated by Django 5.1.7 on 2025-04-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galleries', '0008_rename_event_title_tickets_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='date_of_event',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='venue',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
