# Generated by Django 5.1.7 on 2025-03-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='media',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
