# Generated by Django 5.1.7 on 2025-03-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='from_shop',
            field=models.CharField(default='Nairobi', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.IntegerField(default=254),
        ),
        migrations.AddField(
            model_name='order',
            name='to',
            field=models.CharField(default='Nairobi', max_length=20),
        ),
    ]
