# Generated by Django 5.1.7 on 2025-03-18 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0002_artwork_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='image',
            new_name='artwork_image',
        ),
    ]
