# Generated by Django 5.1.7 on 2025-03-29 20:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
            
            
class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0003_order_from_shop_order_phone_number_order_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='artwork',
        ),
        migrations.AddField(
            model_name='order',
            name='artwork',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Artworks.artwork'),
            preserve_default=False,
        ),
    ]
