# Generated by Django 5.1.7 on 2025-03-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0003_rename_image_artwork_artwork_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='media',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
