# Generated by Django 5.1.7 on 2025-03-29 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0004_remove_orderitem_artwork_order_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='artwork',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Artworks.artwork'),
        ),
    ]
