# Generated by Django 5.1.7 on 2025-03-30 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0005_alter_order_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='artwork',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Artworks.artwork'),
        ),
    ]
