# Generated by Django 5.1.7 on 2025-03-30 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0009_remove_order_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='artwork',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Artworks.artwork'),
        ),
    ]
