# Generated by Django 5.1.7 on 2025-04-17 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0014_mpesapayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='artwork',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Artworks.artwork'),
        ),
    ]
