# Generated by Django 5.1.7 on 2025-04-26 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0016_remove_order_status_order_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='artwork',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Artworks.artwork'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
