# Generated by Django 5.1.7 on 2025-05-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0017_remove_order_is_paid_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
