# Generated by Django 5.1.7 on 2025-05-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0018_artwork_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
