# Generated by Django 5.1.7 on 2025-05-21 08:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0019_artwork_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='likes',
        ),
        migrations.AddField(
            model_name='artwork',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_artworks', to=settings.AUTH_USER_MODEL),
        ),
    ]
