# Generated by Django 5.1.5 on 2025-01-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_image', models.ImageField(upload_to='artist_image')),
                ('artist_name', models.CharField(max_length=100)),
                ('artist_age', models.IntegerField()),
                ('artist_residence', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Search_Events',
        ),
    ]
