# Generated by Django 5.1.7 on 2025-05-02 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artists', '0001_initial'),
        ('Artworks', '0017_remove_order_is_paid_order_payment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artworksubmission',
            name='artwork',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Artworks.artwork'),
        ),
        migrations.AlterUniqueTogether(
            name='artworksubmission',
            unique_together={('artwork', 'artist')},
        ),
    ]
