# Generated by Django 5.1.7 on 2025-05-03 00:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artists', '0002_artworksubmission_artwork_and_more'),
        ('Artworks', '0017_remove_order_is_paid_order_payment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artworksubmission',
            unique_together={('artwork', 'artist', 'gallery')},
        ),
    ]
