# Generated by Django 5.1.7 on 2025-05-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artists', '0003_alter_artworksubmission_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworksubmission',
            name='reviewed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='artworksubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
